### ISSUE TITLE
Close selector's channels on shutdown

### ISSUE THREAD

**Issue by cpiotr** [terma/java-nio-tcp-proxy#12]
When TCP Proxy is shut down, underlying socket remains open.

For example, when a proxy is started:
```
StaticTcpProxyConfig config = new StaticTcpProxyConfig(12345, "github.com", 80);
config.setWorkerCount(1);
TcpProxy proxy = new TcpProxy(config);
proxy.start();
```
it is possible to connect to it using netcat:
```
> echo -e "GET / HTTP/1.0\r\n" | nc localhost 12345
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https:///
Connection: close
```

However, even though the proxy is shut down:
```
proxy.shutdown();
```
It is still possible to connect to socket listening on the specified port:
```
> echo -e "GET / HTTP/1.0\r\n" | nc localhost 12345
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https:///
Connection: close
```

**Comment by cpiotr** [comment]
@terma Thanks for merging the linked pull request! 
Would you have some time to schedule a new release?

**Comment by terma** [comment]
sure, will try today

**Comment by terma** [comment]
it took a lot of time to recover release process, but released https://github.com/terma/java-nio-tcp-proxy/releases/tag/javaniotcpproxy-1.6

**Comment by terma** [comment]
thx again for contribution

**Comment by cpiotr** [comment]
Excellent, thank you for your effort, @terma!
